language: node_js

group: deprecated-2017Q2

node_js: 6

env:
  - CXX=g++-4.8

branches:
  only:
    - master

addons:
  apt:
    sources:
      - elasticsearch-2.4
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - elasticsearch
  hosts:
    - localhost

services:
  - mongodb
  - elasticsearch

before_install:
  - sudo apt-get update && sudo apt-get install sendmail python make g++

before_script:
  - npm install -g grunt-cli
  - sleep 10

script:
  - grunt coverage

